@PhotoshopAutomationApi_HostAddress = http://localhost:5212

GET {{PhotoshopAutomationApi_HostAddress}}/records
Accept: application/json

###

GET {{PhotoshopAutomationApi_HostAddress}}/records/batches
Accept: application/json

###

GET {{PhotoshopAutomationApi_HostAddress}}/records/batches/pending
Accept: application/json